// Copyright 2016 Gerardo Teruel
#ifndef SRC_TAREA02_COMPUTERTYPE_H_
#define SRC_TAREA02_COMPUTERTYPE_H_

enum class ComputerType {DESKTOP, LAPTOP, NETBOOK, TABLET};

#endif  // SRC_TAREA02_COMPUTERTYPE_H_
